image: node:20
variables:
  PROJECT_LOCATION: /opt/applications/ams-imc
  PROJECT_GROUP: simachille
  PROJECT_NETWORK: imc-network
  PROJECT_NAME: front-imc
  PROJECT_VERSION: latest

stages:
 - build
 - test
 - package 
 - deploy

build:
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: "30 days"

.test:
  stage: test
  script:
    - ls -al

.package:
  stage: package
  script:
    - ls -al

build image:
  image: docker:28.1.1
  stage: package
  services:
    - docker:28.1.1-dind
  before_script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
  script:
    - docker build -t $REGISTRY_USERNAME/$PROJECT_NAME:$PROJECT_VERSION .
    - docker push $REGISTRY_USERNAME/$PROJECT_NAME:$PROJECT_VERSION
  after_script:
    - docker images

deploy:
  stage: deploy
  before_script:
    -  chmod 400 $PROD_SERVER_SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $PROD_SERVER_SSH_KEY -p $PROD_SERVER_SSH_PORT $PROD_SERVER_USERNAME@$PROD_SERVER_ADDRESS "mkdir -p $PROJECT_LOCATION/$PROJECT_NAME"
    - scp -o StrictHostKeyChecking=no -i $PROD_SERVER_SSH_KEY -P $PROD_SERVER_SSH_PORT compose.yml $PROD_SERVER_USERNAME@$PROD_SERVER_ADDRESS:$PROJECT_LOCATION/$PROJECT_NAME/compose.yml
    - ssh -o StrictHostKeyChecking=no -i $PROD_SERVER_SSH_KEY -p $PROD_SERVER_SSH_PORT $PROD_SERVER_USERNAME@$PROD_SERVER_ADDRESS "docker network inspect $PROJECT_NETWORK > /dev/null 2>&1 || docker network create $PROJECT_NETWORK"
    - ssh -o StrictHostKeyChecking=no -i $PROD_SERVER_SSH_KEY -p $PROD_SERVER_SSH_PORT $PROD_SERVER_USERNAME@$PROD_SERVER_ADDRESS "docker compose -f $PROJECT_LOCATION/$PROJECT_NAME/compose.yml down && docker compose -f $PROJECT_LOCATION/$PROJECT_NAME/compose.yml up -d"