stages:
  - build
  - package

build:
  stage: build
  before_script:
    - npm ci
    - ls -al
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  after_script:
    - ls -al
    - ls -al dist
    

package:
  stage: package
  script:
    - ls -al
  needs:
    - build