stage: 
  -build
  -test
  -package
  -deploy


build:
  stage: build
  script:
    - npm install
    - npm run build    
test:
  script:
    -echo "test"

package:
  stage: package
  script:
    -echo "test"
    
build image:
  stage: package
  script:
    -echo "test"

deploy:
  stage: deploy
  script:
    -echo "test"
    
    