build:
  script:
    -echo "build"
    
test:
  script:
    -echo "test"

package:
  script:
    -echo "test"
    
build image:
  script:
    -echo "test"

deploy:
  script:
    -echo "test"
    
    