
check:
  stage: .pre
  script:
    - ls -al
clean:
  stage: .post
  script:
    - rm -rf *
build:
  stage: build
  script:
    - echo "build"
test:
  stage: test
  script:
    - echo "test"

package:
  stage: build
  script:
    - echo "test"

build image:
  stage: build
  script:
    - echo "test"

deploy:
  stage: deploy
  script:
    - echo "test"