stage: 
  -package


build:
  stage: build
  script:
    -echo "build"
    
test:
  script:
    -echo "test"

package:
  stage: package
  script:
    -echo "test"
    
build image:
  stage: package
  script:
    -echo "test"

deploy:
  stage: deploy
  script:
    -echo "test"
    
    