image: node:20
stages:
 - build
 - test
 - package
 - deploy

build:
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: "30 days"

test:
  stage: test
  script:
    - ls -al

package:
  stage: package
  script:
    - ls -al

build image:
  image: docker:28.1.1
  stage: package
  services:
    - docker:28.1.1-dind
  script:
    - docker build -t simachille/front-imc:latest .
  after_script:
    - docker images

deploy:
  stage: deploy
  script:
    - ls -al