stages:
  - build
  - package
image: node:21
build:
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - dist
    

package:
  stage: package
  script:
    - CURRENT_VERSION=$(grep version package.json | sed -n 's|.*"version".*:.*"\(.*\)".*|\1|p')
    - echo $CURRENT_VERSION
  needs:
    - build