image: node:21

stages: 
  -build
  -test
  -package
  -deploy


build:
  stage: build
  
  script:
    - npm install
    - npm run build  
  artifacts:
    paths:
      -dist/
    expire_in: "30days"  

test:
  stage: test
  
  script:
    - ls -la

package:
  stage: package
  script:
    - ls -la
    
build image:
  stage: package
  script:
    - ls -la

deploy:
  stage: deploy
  script:
    - ls -la
    
    