image: node:20
variables:
  PROJECT_GROUP: simachille
  PROJECT_NAME: front-imc
  PROJECT_VERSION: latest
debug:
  stage: .pre
  script:
     - env
stages:
 - build
 - test
 - package
 - deploy

build:
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: "30 days"

test:
  stage: test
  script:
    - ls -al

package:
  stage: package
  script:
    - ls -al

build image:
  image: docker:28.1.1
  stage: package
  services:
    - docker:28.1.1-dind
  before_script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
  script:
    - docker build -t $REGISTRY_USERNAME/$PROJECT_NAME:$PROJECT_VERSION .
    - docker push $REGISTRY_USERNAME/$PROJECT_NAME:$PROJECT_VERSION
  after_script:
    - docker images

deploy:
  stage: deploy
  script:
    - ls -al