image: node:20
stages:
 - build
 - test
 - package
 - deploy

build:
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: "30 days"

test:
  stage: test
  script:
    - ls -al

package:
  stage: package
  script:
    - ls -al

build image:
  stage: package
  script:
    - ls -al

deploy:
  stage: deploy
  script:
    - ls -al