image: node:20
stages:
 - build
 - test
 - package
 - deploy

build:
  stage: build
  script:
    - npm ci
    - ls -al
    - npm run build

test:
  stage: test
  script:
    - ls -al

package:
  stage: package
  script:
    - ls -al

build image:
  stage: package
  script:
    - ls -al

deploy:
  stage: deploy
  script:
    - ls -al