image: node:20
stages:
 - build
 - test
 - package
 - deploy

install:
  stage: build
  script:
    - npm ci

build:
  stage: build
  script:
    - ls -al
  needs:
    - install

test:
  stage: test
  script:
    - ls -al

package:
  stage: package
  script:
    - ls -al

build image:
  stage: package
  script:
    - ls -al

deploy:
  stage: deploy
  script:
    - ls -al