image: node:20
stages:
 - build
 - test
 - package
 - deploy

build:
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  after_script:
    - ls -al 
    - ls -al dist

test:
  stage: test
  script:
    - ls -al

package:
  stage: package
  script:
    - ls -al

build image:
  stage: package
  script:
    - ls -al

deploy:
  stage: deploy
  script:
    - ls -al