services:
  front-imc:
    image: simachille/front-imc:latest
    container_name: front-imc
    ports:
      - 3001:80
    networks:
      - imc-network

networks:
  imc-network:
    name: imc-network
    external: true
