name: CI Pipeline

env:
  PROJECT_GROUP: moladevopsgroup
  PROJECT_NAME: front-imc
  PROJECT_VERSION: latest
  DOCKER_USERNAME: moladevops237

on:
  push:
    branches: [ main, features/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: npm install
    
    - name: Build application
      run: npm run build
    
    - name: Upload node_modules
      uses: actions/upload-artifact@v4
      with:
        name: node-modules
        path: node_modules/
    
    - name: Upload dist
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download node_modules
      uses: actions/download-artifact@v4
      with:
        name: node-modules
        path: node_modules/
    
    - name: Run tests
      run: ls -la

  package:
    runs-on: ubuntu-latest
    container:
      image: node:20
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download dependencies
      uses: actions/download-artifact@v4
      with:
        name: node-modules
        path: node_modules/
    
    - name: Package application
      run: ls -la
  
  build-image:
    runs-on: ubuntu-latest
    needs: package
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      run: |
        docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ github.sha }} .
        docker push ${{ env.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ github.sha }}
        docker tag ${{ env.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ github.sha }} ${{ env.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }}
        docker push ${{ env.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    
    steps:
    - uses: actions/checkout@v4
    - name: Deploy info
      run: |
        echo "Project: ${{ env.PROJECT_GROUP }}/${{ env.PROJECT_NAME }}"
        echo "Version: ${{ env.PROJECT_VERSION }}"
        echo "Image: ${{ env.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ github.sha }}"