name: CI Pipeline
# Force update: 2025-10-04

on:
  push:
    branches: [ main, features/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: npm install
    
    - name: Build application
      run: npm run build
    
    - name: Upload node_modules
      uses: actions/upload-artifact@v4
      with:
        name: node-modules
        path: node_modules/
    
    - name: Upload dist
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download node_modules
      uses: actions/download-artifact@v4
      with:
        name: node-modules
        path: node_modules/
    
    - name: Run tests
      run: ls -la

  package:
    runs-on: ubuntu-latest
    container:
      image: node:20
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download dependencies
      uses: actions/download-artifact@v4
      with:
        name: node-modules
        path: node_modules/
    
    - name: Package application
      run: ls -la

  build-image:
    runs-on: ubuntu-latest
    needs: package
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t moladevops/front-imc:${{ github.sha }} .
    
    - name: List Docker images
      run: docker images

  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:20
    needs: build-image
    
    steps:
    - uses: actions/checkout@v4
    - run: ls -la